Update ODK to v1.3.0
EBISPOT/scatlas_ontology pull request #23
Opened 2022-03-09 15:15 UTC by anitacaron

2022-03-10 08:35 UTC, matentzn requested changes

2022-03-10 08:35 UTC, matentzn commented on .github/workflows/qc.yml
> +    branches: [ main ]
wrong branch name. (`master`)

2022-03-10 08:35 UTC, matentzn commented on .github/workflows/qc.yml
> +    branches: [ main ]
wrong branch name. (`master`)

2022-03-10 08:35 UTC, matentzn commented on .github/workflows/qc.yml
> +          DEFAULT_BRANCH: main
wrong branch name. (`master`)

2022-03-10 08:35 UTC, matentzn commented on src/sparql/SCAtlas_terms.sparql
>    { ?s1 ?p1 ?term . }
The fact that the finalname here has casing suggests a bug in ODK - maybe make an issue at ODK to ensure filenames using the ontology ID should be cycled through "lower". I noticed this also for the release artefacts..

2022-03-10 08:35 UTC, matentzn commented on src/sparql/SCAtlas_terms.sparql
>    { ?s1 ?p1 ?term . }
alternatively change the id in the scao rather than SCAtlas?

2022-03-10 11:06 UTC, anitacaron commented on src/sparql/SCAtlas_terms.sparql
>    { ?s1 ?p1 ?term . }
the id in the yaml file is already scao

2022-03-10 13:32 UTC, anitacaron commented on src/sparql/SCAtlas_terms.sparql
>    { ?s1 ?p1 ?term . }
it worked! Thanks

2022-03-11 12:10 UTC, matentzn approved these changes
Nice work!

2022-03-11 12:12 UTC, merged