WIP: Update ODK and refactor the pipeline a bit
EBISPOT/scatlas_ontology pull request #32
Opened 2022-07-28 12:08 UTC by matentzn

2022-07-28 19:09 UTC, gouttegd requested changes

2022-07-28 19:09 UTC, gouttegd commented on src/ontology/scatlas.Makefile
> +	if [ $(IMP) = true ]; then $(ROBOT) merge --input imports/fbbt_import.owl reason --reasoner ELK relax \
I think the `if [ $(IMP) = true ]` is no longer appropriate here.

Now, components are generated when the `all_components` target is invoked explicitly. But in the `run_release.sh` script, that target is invoked with `IMP=false`:

```sh
sh run.sh make IMP=false all_components -B
```

This makes sense since we have just refreshed the imports explicitly (that’s the previous line in `run_release.sh`), but this means that the code to generate the `fbbt.owl` component is never executed.

Now that components are, in effect, disconnected from the imports, the generation of the `fbbt.owl` component should not be tied to the `IMP` variable.

2022-07-28 19:09 UTC, gouttegd commented on src/ontology/scatlas.Makefile
> +	if [ $(IMP) = true ]; then $(ROBOT) merge --input imports/omit_import.owl relax remove --axioms disjoint reason --reasoner ELK \
Same as above.

2022-07-28 19:13 UTC, gouttegd commented
Of note, when I tested this PR, the main mirroring issue was caused not by `CHEBI` (though it did cause some issues, but in the end I was able to download the full file), but by `ncbitaxon`: I was _never_ able to download the full ~1.8GB file, no matter how many times I tried…

In the end, to bypass the issue I changed the mirror URL to `http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl` (that’s also what we do in Uberon).

Is there a compelling reason for using the full `ncbitaxon.owl` file?

2022-07-29 10:17 UTC, matentzn commented on src/ontology/scatlas.Makefile
> +	if [ $(IMP) = true ]; then $(ROBOT) merge --input imports/fbbt_import.owl reason --reasoner ELK relax \
Adressed here: https://github.com/EBISPOT/scatlas_ontology/commit/f341812d5fc76744f7a1f286194d14d3e1fde8f1

2022-07-29 10:17 UTC, matentzn commented on src/ontology/scatlas.Makefile
> +	if [ $(IMP) = true ]; then $(ROBOT) merge --input imports/omit_import.owl relax remove --axioms disjoint reason --reasoner ELK \
Adressed here: https://github.com/EBISPOT/scatlas_ontology/commit/f341812d5fc76744f7a1f286194d14d3e1fde8f1

2022-07-29 10:38 UTC, matentzn commented
Unfortunately we cannot use ncbitaxon slim because it is missing about 100 taxa. I switched to ncbitaxon.obo which has everything we want, but is much smaller.

2022-07-29 11:39 UTC, gouttegd commented
Oh, there’s a weird thing here: when I try to download the `ncbitaxon.obo` file, ROBOT errors out as if it had been given a HTML file:

```
Parser: org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser@6f0cb5a1
    Stack trace:
LINENO: 1 - Could not find tag separator ':' in line.
LINE: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">        org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:60)
```

but if I download `http://purl.obolibrary.org/obo/ncbitaxon.obo` manually beforehand, I do get an OBO file as expected…

2022-07-29 14:03 UTC, gouttegd commented
I am not sure what’s happening, but ROBOT seems to have trouble following HTTP redirections…

```sh
robot convert -I http://purl.obolibrary.org/obo/ncbitaxon.obo -o ncbitaxon.owl
```

fails with the aforementioned error.

That URL is redirected to `https://github.com/obophenotype/ncbitaxon/releases/latest/download/ncbitaxon.obo`. Using that redirected URL directly works:

```sh
robot convert -I https://github.com/obophenotype/ncbitaxon/releases/latest/download/ncbitaxon.obo -o ncbitaxon.owl
```

This is not specific to `ncbitaxon.obo`. I observe the same behaviour with, for example, `wbls.obo`: ROBOT can’t load the ontology from `http://purl.obolibrary.org/obo/wbls.obo`, but it succeeds if I specify directly the redirected URL `https://raw.githubusercontent.com/obophenotype/c-elegans-development-ontology/master/wbls.obo`.

But (even weirder!) it does seem to be specific to the OBO format:

```sh
robot convert -I http://purl.obolibrary.org/obo/wbls.owl -o wbls.owl
```

works.

2022-07-29 14:06 UTC, gouttegd commented
I worked around the issue by manually downloading `ncbitaxon.obo`, and the rest seems to work.

2022-07-29 15:50 UTC, matentzn commented
Ok I am using now a config in ODK that should deal with the ncbitaxon issue. Hopefully once and for all.

2022-07-29 15:57 UTC, gouttegd approved these changes

2022-07-29 17:57 UTC, merged